# Generated by Django 2.1.3 on 2018-11-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('data_evento', models.DateTimeField()),
            ],
            options={
                'db_table': 'orcamento',
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='plano',
            old_name='intens',
            new_name='itens',
        ),
        migrations.AddField(
            model_name='orcamento',
            name='planos',
            field=models.ManyToManyField(to='contratos.Plano'),
        ),
    ]
