# Generated by Django 2.1.3 on 2018-11-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_auto_20181115_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='email',
            field=models.EmailField(max_length=70),
        ),
    ]
